### ISSUE TITLE
How to get value?

### ISSUE THREAD

**Issue by isaachinman** [algolia/react-nouislider#10]
Obviously initiating a slider via react-nouislider doesn't allow for the noUiSlider.get() method. How can we programmatically access the min/max values of a slider? I would ideally like to be able to get this value directly from the DOM, eg `$('some-slider').val()`.

**Comment by vvo** [comment]
If we ever expose this get method it would be in a React way but that I do not know how, any idea @bobylito?

Otherwise, what you can do right now is use events: https://github.com/algolia/react-nouislider/blob/master/index.js#L18
- props.onUpdate
- props.onSlide
- props.onChange

They all relate to http://refreshless.com/nouislider/events-callbacks/

**Comment by isaachinman** [comment]
@vvo Thanks, but what point is there in an onSlide event if you can't return the value?

**Comment by vvo** [comment]
From reading the nouislider configuration I think inside the event listener you can use this.get() to get the actual values.

And even the arguments should contain all the information you need: http://refreshless.com/nouislider/events-callbacks/#section-binding

let me know

**Comment by isaachinman** [comment]
Yup, it works with the three events you've defined. Cheers.

**EDIT:** `this.get is not a function`. Not yet sure if this is a scope problem or an issue with the actual component.

**Comment by vvo** [comment]
Might be a binding issue, wanna help sovling it?

**Comment by backnotprop** [comment]
I used `ref` for this.

``` javascript
<Nouislider
    range={{
        min: 0,
        max: 7
    }}
    onSlide={this.onChangeSlide.bind(this)}
    ref="NoUiSlider"
/>
```

and within the ref object you can access `slider.get()`

``` javascript
onChangeSlide(){
    console.log(this.refs.NoUiSlider.slider.get()) // logs the value
}
```

**Comment by vvo** [comment]
Awesome, thanks for feedback!!!

**Comment by asherwebb** [comment]
I am able to get the onSlide property to work. This is dispatching an action to a redux store in my case and I am able to successfully capture the range low and range high values. The only issue is that the handles will not move - as if the components onSlide property was providing for the handle animation and placement and by 'hijacking' this prop to be used by react that functionality is broken

**Comment by vvo** [comment]
Maybe you need the default nouislider css? https://github.com/leongersen/noUiSlider/blob/master/distribute/nouislider.css

If so, can you add this to the documentation? Thanks.

**Comment by asherwebb** [comment]
Thank you for the advise. I had the css in my code. After examining it looks like the problem is that the `<Nouislider />` object is re-rendering every time the onSlide event fires.

**Comment by vvo** [comment]
Yes, clearly I would advise now to use the airbnb slider which is full react and better suited, http://airbnb.io/projects/rheostat/

**Comment by asherwebb** [comment]
Cool thanks again - I will check that out! If anyone else has the same issue I got it to work by passing props for the start/stop placement of the handles like:
```const PriceSlider = (props) => {
  let handlePlacement = [props.rangestart, props.rangestop]
  return (
    <div className="noui-slider">
      <Nouislider
        range={{min: 0, max: 50000}}
        start={handlePlacement}
        step={1000}
        connect={true}
        onSlide={props.onChangeSlide}
      />
    </div>
  )
}```

**Comment by asherwebb** [comment]
Cool thanks again - I will check that out! If anyone else has the same issue I got it to work by passing props for the start/stop placement of the handles like:
`const PriceSlider = (props) => {
  let handlePlacement = [props.rangestart, props.rangestop]
  return (
    <div className="noui-slider">
      <Nouislider
        range={{min: 0, max: 50000}}
        start={handlePlacement}
        step={1000}
        connect={true}
        onSlide={props.onChangeSlide}
      />
    </div>
  )
}`

**Comment by asherwebb** [comment]
const PriceSlider = (props) => {
  let handlePlacement = [props.rangestart, props.rangestop]
  return (
    <div className="noui-slider">
      <Nouislider
        range={{min: 0, max: 50000}}
        start={handlePlacement}
        step={1000}
        connect={true}
        onSlide={props.onChangeSlide}
      />
    </div>
  )
}

**Comment by asherwebb** [comment]
let handlePlacement = [props.rangestart, props.rangestop]
<Nouislider 
start={handlePlacement}
/>

**Comment by asherwebb** [comment]
Cool thanks again - I will check that out. Got it working by passing in start array params based on props gathered by onSlide 💯
