### ISSUE TITLE
Error when implementing inside another component

### ISSUE THREAD

**Issue by magupisoft** [algolia/react-nouislider#15]
I am using this component as a filter along with React Boostrap Table, and when I try to run it in Browser, I get the following error: 

 ReferenceError: window is not defined
   at <anonymous>:148:12 -> actions = window.navigator.pointerEnabled ? {
   at array.filter.a.(anonymous function).(anonymous function) (<anonymous>:8:210)
   at <anonymous>:21:2
   at Script Document [3]:4:17239
   at Q (Script Document [3]:1:518)
   at <anonymous>:19:19
   at Script Document [3]:4:48
   at Q (Script Document [3]:1:518)
   at <anonymous>:33:24
   at Script Document [3]:3:12578
   at Q (Script Document [3]:1:518)
   at <anonymous>:41:20
   at Script Document [3]:2:7045
   at Q (Script Document [3]:1:518)
   at <anonymous>:29:20
   at Script Document [3]:1:2835
   at Q (Script Document [3]:1:518)
   at <anonymous>:9:23
   at Script Document [3]:1:657
   at Q (Script Document [3]:1:518)
   at Script Document [3]:1:605
   at Script Document [3]:1:610
   at Script Document [3]:1:308
   at Script Document [3]:1:330
Line: 4
Column: 17239

**Comment by vvo** [comment]
Can you build a reproducible repo where I can see the error? We are using this module with success in https://github.com/algolia/instantsearch.js/tree/master/src/components/Slider

window in a browser should always be defined, maybe we are missing something here

**Comment by magupisoft** [comment]
I think this is too old, may be it is already fixed, given that this happened one year ago. Thank you
