### ISSUE TITLE
Does not support server-side rendering

### ISSUE THREAD

**Issue by danieldunderfelt** [algolia/react-nouislider#19]
Hi!

I tried to use this in a project where server-side rendering is used, but nouiSlider wants to access the `window` object. Can this be solved such that react-nouislider is essentially a no-op if `window` is not available?

Thanks!

**Comment by vvo** [comment]
react-nouislider only wraps https://github.com/leongersen/noUiSlider in a react component so I dunno the work needed to do so.

On a more general question, do you know any slider working "server-side"? What does it means for a slider to work server side?

**Comment by gabrielflorit** [comment]
@danieldunderfelt this is fixed on noUiSlider master: https://github.com/leongersen/noUiSlider/pull/503

**Comment by vvo** [comment]
Pushed a new version, let me know
