### ISSUE TITLE
Formatting of tooltips

### ISSUE THREAD

**Issue by kambanwait** [algolia/react-nouislider#20]
I've tried a few different ways of setting the format of tooltips but is there a way of only showing a whole number with no decimal point?

**Comment by vvo** [comment]
You can use step = 1 propType, this should only show whole numbers.

Otherwise, use:

``` jsx
tooltips = {{to: function(value) {
  return Math.round(parseInt(value));
}}}
```

**Comment by kambanwait** [comment]
Thank you. I think this should be added to the Readme. I wouldn't have guessed this at all.

**Comment by kambanwait** [comment]
Sorry, but just noticed this when I use the answer you supplied:

`Warning: Failed propType: Invalid prop`tooltips`supplied to`Nouislider`. Check the render method of`exports`.`

I've got the following:
`<Nouislider
                orientation="vertical"
                onSlide={this.onChangeSlide}
                ref="NoUiSlider"
                range={{
                    min: 0,
                    max: 100
                }}
                start={[0]}
                step={1.0}
                pips={{
                    mode: 'values',
                    values: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
                    density: 1
                }}
                tooltips={{to: function(value){
                    return Math.round(parseInt(value));
                }}}
            />`

That should, in theory, be ok?

**Comment by vvo** [comment]
Can you try:

``` jsx
tooltips = {[{to: function(value) {
  return Math.round(parseInt(value));
}}]}
```

**Comment by kambanwait** [comment]
@vvo Perfect! That's stopped the warning! :)

**Comment by vvo** [comment]
Cool!

**Comment by pixelastic** [comment]
@vvo: Don't you think it should go into the readme?

**Comment by vvo** [comment]
What we can do is link to the nouislider readme because all the options are just forwarded to nouislider: 
- http://refreshless.com/nouislider/slider-options/#section-tooltips
- http://refreshless.com/nouislider/slider-read-write/#section-formatting
