### ISSUE TITLE
Using "Tooltips" is giving Warning in console

### ISSUE THREAD

**Issue by kambanwait** [algolia/react-nouislider#21]
When I use the following:

`<Nouislider tooltips={{to: function(value){return Math.round(parseInt(value));}}} />`

I'm presented with the following warning in console:

`Warning: Failed propType: Invalid prop`tooltips`supplied to`Nouislider`. Check the render method of`exports`.`

**Comment by vvo** [comment]
duplicate of #20 lets solve this here
