### ISSUE TITLE
Flickering on re-render

### ISSUE THREAD

**Issue by njbarrett** [algolia/react-nouislider#23]
Firstly thank you for this great react implementation of nouislider.

I am having some flickering issues when my component re-renders. It's just enough to be annoying, like the bar flickers everything I update the state.

Is there a way to prevent this?

**Comment by vvo** [comment]
Hi, thanks for reporting this, I cannot see the issue right here: https://community.algolia.com/instantsearch.js/examples/tourism/

Could you maybe submit a jsfiddle or codepen?

**Comment by njbarrett** [comment]
Yeah, I cant reproduce it on there. It could be because I am rendering a lot of sliders and a map on the page and its too much for the browser to render at once so it shows a split second where the start and and slider "handles" are both at the start of the slider bar.
If I can reproduce it on a codepen or similar I will reopen.

**Comment by vvo** [comment]
Truth being that the nouislider instance and DOM will be added/removed at every re-render and this might (should) be an issue. We are looking forward at a native react slider if you feel like coding it ;D

**Comment by vvo** [comment]
There's now a slider with a lot of shared features with nouislider: http://react-component.github.io/slider/
