### ISSUE TITLE
Getting the end event

### ISSUE THREAD

**Issue by d-winter** [algolia/react-nouislider#26]
Hi.
Is it possible to get the 'end' event when the user stops moving the slider?
Only found a way to get the events while moving.
Thanks a lot.
Daniel

**Comment by redox** [comment]
Oh yes, I think it's easily doable adding the `end` (maybe `start` as well, see [doc](http://refreshless.com/nouislider/events-callbacks/)) events forwarding [here](https://github.com/algolia/react-nouislider/blob/master/index.js#L22-L36).

Do you want to try a PR @d-winter?

**Comment by d-winter** [comment]
Hi @redox .
Yes, I can do. Have not made any pull requests before.
Thanks for your feedback!

**Comment by redox** [comment]
Has been released in `1.12.0`. Thank you for your help @d-winter 👍

**Comment by d-winter** [comment]
Hey @redox,
thanks for the fast merge and release 👍
Have a nice day!
