### ISSUE TITLE
Connect PropTypes have changed

### ISSUE THREAD

**Issue by patrickdevivo** [algolia/react-nouislider#31]
See: https://github.com/algolia/react-nouislider/blob/master/index.js#L60-L64

And: https://refreshless.com/nouislider/slider-options/#section-Connect

Looks like the options for the underlying noUiSlider have changed to `boolean` or `[boolean]`

**Comment by patrickdevivo** [comment]
Fixed by: https://github.com/algolia/react-nouislider/pull/32

**Comment by vvo** [comment]
done
