### ISSUE TITLE
Not working with React 16 due to use of propTypes from React, need to use 'prop-types' module to make it compatible

### ISSUE THREAD

**Issue by danday74** [algolia/react-nouislider#39]
This is preventing me from upgrading to React 16.

Please could you switch to using the 'prop-types' package to make this work with React 16. Thanks.

**Comment by Haroenv** [comment]
Sorry we are not maintaining this repository anymore for now, feel free to do a pull request though, it should be easy with a codemod: https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types

**Comment by danday74** [comment]
ok thanks for heads up. I won't have time to look at this right now but prob will get round to it in a few months. Hopefully, someone can beat me to it. If we can leave this open for now would be appreciated.

**Comment by Haroenv** [comment]
It wasn't much work so I did it myself, can you try out to see if https://github.com/algolia/react-nouislider/pull/40 works? it works perfectly for me @danday74

**Comment by Haroenv** [comment]
Released as `2.0.1` with compat for react 16

**Comment by danday74** [comment]
Many thanks for this - I will let you know if I hit any probs but am sure its all good - your work is much appreciated, another obstacle blocking our react 16 upgrade path removed :)
