### ISSUE TITLE
onSlide event?

### ISSUE THREAD

**Issue by sean-clayton** [algolia/react-nouislider#7]
I recently discovered that rerendering onUpdate will make react behave poorly, because `update` is fired immediately onload. If using `update` for rendering something, `update` will trigger a rerender, which will trigger `update`, which triggers a rerender, and yadda yadda yadda.

`on('slide')`, on the other hand, does _not_ fire on rerender—only on a slide event (obviously).

I'm willing to add this functionality to the slider if y'all are accepting pull requests :)

**Comment by redox** [comment]
Released in `1.7.0`. Thank you for your help @sean-clayton :100:

**Comment by elinake** [comment]
How exactly this is supposed to work, because now the dragging doesn't update the slider movement before dragging stops, and that is obviously not wanted behavior?

**Comment by vvo** [comment]
Hi @elinake, can you open a new issue describing your problem in details? Since this is an old issue. Thanks

**Comment by vvo** [comment]
Also most probably you might want to check https://github.com/leongersen/noUiSlider directly.

**Comment by binjospookie** [comment]
@vvo according to @elinake I pass smth like:
```
onSlide={(data) => {console.log(data}}
```
And when I drag slider's hands I see console.log, but slider's hands don't move.

**Comment by vvo** [comment]
Hey can you open a new issue and demonstrate your problem in a repository, or even as a PR of this repository?

Thanks

**Comment by binjospookie** [comment]
My problem was resolved. I can write smth like "How to resolve" if it necessary.

It's not about wrapper's code. It's like guide.
