### ISSUE TITLE
Remove decimals?

### ISSUE THREAD

**Issue by isaachinman** [algolia/react-nouislider#9]
Can't figure out how to remove decimals on the React component, any ideas? 

This doesn't work:

```
format: wNumb({
    decimals: 0,
})
```

**Comment by vvo** [comment]
I am sorry I did not fully understand your issue, can you be more specific in what you are trying to do on a UX level? Then we can see what's the underlying code solution

**Comment by ItsMrAkhil** [comment]
Can I remove the decimal from the tooltip of the noUISlider by passing 
format: wNumb({
    decimals: 0,
})
as a prop to the noUISlider?

**Comment by vvo** [comment]
See here to format the value: https://github.com/algolia/react-nouislider/issues/20#issuecomment-209517590

**Comment by jeromemalot** [comment]
Yes of course you can pass it as a prop but you need first to import wNumb which is an independant [library](https://www.npmjs.com/package/wnumb). 

`import wNumb from 'wnumb'`


`                        <Nouislider
                            range={{min: 1, max: 10}}
                            start={[2, 6]}
                            tooltips 
                            step={1}
                            format={
                                wNumb({
                                    decimals: 0
                                })
                            }
                        />`
